### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ChampOfGamesYT** [Wertzui123/ChangeDisplayName#1]
If I use PurePerms  would be there a problem?

**Comment by tim03we** [comment]
Er fragt nach Hilfe und alles drum und dran und dann wird man noch nicht mal verlinkt... Frechheit.

**Comment by ChampOfGamesYT** [comment]
Was meinst du?

**Comment by Wertzui123** [comment]
@tim03we Sorry, aber geholfen hast du mir nie...

**Comment by Wertzui123** [comment]
No, that's one of the nice Features. It works with PurePerms and PureChat @ChampOfGamesYT
