### ISSUE TITLE
/realname and /unnick

### ISSUE THREAD

**Issue by Wertzui123** [Wertzui123/ChangeDisplayName#2]
Add /realname!

**Comment by Wertzui123** [comment]
And /unnick

**Comment by Wertzui123** [comment]
Test

**Comment by Baducai** [comment]
Wie lange wird es noch ungefähr dauern?

**Comment by Wertzui123** [comment]
Ich arbeite gerade an dem Clan Plugin, und einem für meinen Server. Ich werds irgendwann mal machen, ich hoffe ich finde bald Zeit,,,

**Comment by Baducai** [comment]
@Wertzui123 Suchst du noch für deinen Server einen Developer?

**Comment by Wertzui123** [comment]
Na gerne, kann immer hilfe gebrauchen. Das kannst du mich aber bitte über Discord fragen, icj glaube hier stört es nur die anderen.

**Comment by Wertzui123** [comment]
Added in 3.0

https://github.com/Wertzui123/ChangeDisplayName/releases/tag/3.0
